name: Deploy To Server Docker

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ftp_transfer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Inicializar transferencia FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 181.39.238.180
          username: ubuntu
          port: 222
          protocol: sftp
          server-dir: /home/ubuntu/andres/web/
          password: ${{ secrets.SFTP_PASS_RASBERRY }}
          security: loose